# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener:  'force'
    serializer:
        serialize_null: true
    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader:
        include_format: false
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: json }
